# Generated by Django 5.1.2 on 2024-10-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_posts',
            new_name='blog_post',
        ),
        migrations.RenameField(
            model_name='blog_name',
            old_name='blog_name',
            new_name='b_name',
        ),
    ]
