# Generated by Django 5.1.2 on 2024-10-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_like_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
