# Generated by Django 5.1.2 on 2024-10-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_blog_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='liked',
        ),
    ]
