# Generated by Django 5.1.2 on 2024-10-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_remove_blog_post_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='post_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
